
## modify the path
BWA_INDEX: PathTo/hg38.fa
frag_path: PathTo/hg38_cviqi.bed
chromsizes : PathTo/hg38.chrom.sizes
genome: hg38
cool_bin: 10000

SAMPLES_JSON: './samples.json'
CLUSTER_JSON: './cluster.json'
